#!/usr/bin/env python3
"""
Interactive AnyRouter account manager for Claude Code and Codex.

Reads .accounts.json, lists account balances (same API as checkin.py), and switches
the active auth_token for local Claude Code / Codex usage.
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import io
import json
import os
import re
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx
from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.prompt import Prompt
from rich.table import Table
from rich.text import Text

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from accounts_utils import load_accounts_file, refresh_api_users

from checkin import get_user_info, parse_cookies, prepare_cookies
from utils.config import AccountConfig, AppConfig

console = Console()
error_console = Console(stderr=True)

STATE_DIR = Path.home() / '.config' / 'anyrouter-check-in'
DEFAULT_ACCOUNTS_FILE_NAME = '.accounts.json'
CONFIG_ACCOUNTS_FILE = STATE_DIR / 'accounts.json'
ACTIVE_STATE_FILE = STATE_DIR / 'active.json'
ENV_EXPORT_FILE = STATE_DIR / 'env.sh'
CLAUDE_DIR = Path.home() / '.claude'
CLAUDE_SETTINGS_FILE = CLAUDE_DIR / 'settings.json'
CODEX_DIR = Path.home() / '.codex'
CODEX_AUTH_FILE = CODEX_DIR / 'auth.json'
CODEX_CONFIG_FILE = CODEX_DIR / 'config.toml'
DEPLOY_SCRIPT_FILE = Path.home() / 'Downloads' / 'anyrouter-deploy-current.sh'
DEFAULT_BASE_URL = 'https://a-ocnfniawgw.cn-shanghai.fcapp.run'
CODEX_CONFIG_TEMPLATE = """model = "gpt-5.5"
model_provider = "anyrouter"
preferred_auth_method = "apikey"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[model_providers.anyrouter]
name = "Any Router"
base_url = "{base_url}/v1"
wire_api = "responses"
"""
ZSHRC_HOOK_START = '# >>> anyrouter-check-in >>>'
ZSHRC_HOOK_END = '# <<< anyrouter-check-in <<<'
ZSHRC_FILE = Path.home() / '.zshrc'
DEPLOY_SCRIPT_TEMPLATE = r"""#!/usr/bin/env bash
set -euo pipefail

# Generated by anyrouter_accounts.py after switching the active account.
# Copy this file into a dev container or another host and run it directly.

ACTIVE_ACCOUNT_NAME={account_name}
ACTIVE_ACCOUNT_INDEX={account_index}
ANYROUTER_AUTH_TOKEN={auth_token}
ANYROUTER_BASE_URL={base_url}
CODEX_MODEL={codex_model}
CODEX_PROVIDER={codex_provider}

STATE_DIR="${{HOME}}/.config/anyrouter-check-in"
ENV_FILE="${{STATE_DIR}}/env.sh"
ACTIVE_FILE="${{STATE_DIR}}/active.json"
CLAUDE_DIR="${{HOME}}/.claude"
CLAUDE_SETTINGS_FILE="${{CLAUDE_DIR}}/settings.json"
CODEX_DIR="${{HOME}}/.codex"
CODEX_AUTH_FILE="${{CODEX_DIR}}/auth.json"
CODEX_CONFIG_FILE="${{CODEX_DIR}}/config.toml"
NPM_USER_PREFIX="${{NPM_CONFIG_PREFIX:-${{HOME}}/.npm-global}}"
NEEDS_NPM_USER_PATH=0

HOOK_START='# >>> anyrouter-check-in >>>'
HOOK_END='# <<< anyrouter-check-in <<<'

backup_file() {{
  local path="$1"
  if [[ -f "$path" ]]; then
    cp "$path" "${{path}}.bak.$(date +%Y%m%d%H%M%S)"
  fi
}}

json_escape() {{
  local value="$1"
  value=${{value//\\/\\\\}}
  value=${{value//\"/\\\"}}
  value=${{value//$'\n'/\\n}}
  printf '%s' "$value"
}}

ensure_npm_available() {{
  if command -v npm >/dev/null 2>&1; then
    return 0
  fi

  printf 'ERROR: npm is required to install missing Claude Code/Codex clients.\n' >&2
  printf 'Install Node.js/npm first, then rerun this deploy script.\n' >&2
  return 1
}}

prepend_path_once() {{
  local dir="$1"
  case ":$PATH:" in
    *":$dir:"*) ;;
    *) export PATH="$dir:$PATH" ;;
  esac
}}

install_npm_cli() {{
  local label="$1"
  local binary="$2"
  local package="$3"

  if command -v "$binary" >/dev/null 2>&1; then
    printf '%s found: %s\n' "$label" "$(command -v "$binary")"
    return 0
  fi

  ensure_npm_available
  printf '%s not found; installing %s...\n' "$label" "$package"

  if npm install -g "$package"; then
    hash -r 2>/dev/null || true
  fi

  if command -v "$binary" >/dev/null 2>&1; then
    printf '%s installed: %s\n' "$label" "$(command -v "$binary")"
    return 0
  fi

  printf 'Global npm install did not expose %s; retrying with user prefix %s...\n' "$binary" "$NPM_USER_PREFIX"
  mkdir -p "$NPM_USER_PREFIX"
  NPM_CONFIG_PREFIX="$NPM_USER_PREFIX" npm install -g "$package"
  prepend_path_once "$NPM_USER_PREFIX/bin"
  NEEDS_NPM_USER_PATH=1
  hash -r 2>/dev/null || true

  if ! command -v "$binary" >/dev/null 2>&1; then
    printf 'ERROR: %s installation finished but %s is still not on PATH.\n' "$label" "$binary" >&2
    printf 'Expected binary under %s/bin. Check npm output above.\n' "$NPM_USER_PREFIX" >&2
    return 1
  fi

  printf '%s installed: %s\n' "$label" "$(command -v "$binary")"
}}

ensure_clients() {{
  install_npm_cli 'Claude Code' 'claude' '@anthropic-ai/claude-code'
  install_npm_cli 'Codex CLI' 'codex' '@openai/codex'
}}

ensure_shell_hook() {{
  local rc_file="$1"
  local tmp_file

  mkdir -p "$(dirname "$rc_file")"
  touch "$rc_file"
  backup_file "$rc_file"
  tmp_file="$(mktemp)"

  awk -v start="$HOOK_START" -v end="$HOOK_END" '
    $0 == start {{ skip = 1; next }}
    $0 == end {{ skip = 0; next }}
    skip == 1 {{ next }}
    /^[[:space:]]*export[[:space:]]+ANTHROPIC_AUTH_TOKEN=/ {{ next }}
    /^[[:space:]]*export[[:space:]]+ANTHROPIC_BASE_URL=/ {{ next }}
    /^[[:space:]]*export[[:space:]]+CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=/ {{ next }}
    /^[[:space:]]*export[[:space:]]+CLAUDE_CODE_ATTRIBUTION_HEADER=/ {{ next }}
    {{ print }}
  ' "$rc_file" > "$tmp_file"

  {{
    cat "$tmp_file"
    printf '\n%s\n' "$HOOK_START"
    printf '# Managed by anyrouter deploy script\n'
    printf '[[ -f "%s" ]] && source "%s"\n' "$ENV_FILE" "$ENV_FILE"
    printf '%s\n' "$HOOK_END"
  }} > "$rc_file"

  rm -f "$tmp_file"
}}

write_codex_config() {{
  local base_v1="${{ANYROUTER_BASE_URL%/}}/v1"

  mkdir -p "$CODEX_DIR"
  if [[ -f "$CODEX_CONFIG_FILE" ]]; then
    backup_file "$CODEX_CONFIG_FILE"
  fi

  if [[ ! -f "$CODEX_CONFIG_FILE" ]]; then
    cat > "$CODEX_CONFIG_FILE" <<EOF
model = "${{CODEX_MODEL}}"
model_provider = "${{CODEX_PROVIDER}}"
preferred_auth_method = "apikey"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[model_providers.anyrouter]
name = "Any Router"
base_url = "${{base_v1}}"
wire_api = "responses"
EOF
    return
  fi

  awk -v model="$CODEX_MODEL" -v provider="$CODEX_PROVIDER" -v base_url="$base_v1" '
    BEGIN {{
      wrote_model = 0
      wrote_provider = 0
      wrote_auth = 0
      wrote_approval = 0
      wrote_sandbox = 0
      emitted_root = 0
      seen_section = 0
    }}
    function emit_missing_root() {{
      if (emitted_root) return
      if (!wrote_model) print "model = \"" model "\""
      if (!wrote_provider) print "model_provider = \"" provider "\""
      if (!wrote_auth) print "preferred_auth_method = \"apikey\""
      if (!wrote_approval) print "approval_policy = \"never\""
      if (!wrote_sandbox) print "sandbox_mode = \"danger-full-access\""
      emitted_root = 1
    }}
    /^\[model_providers\.anyrouter\]$/ {{ skip_anyrouter = 1; next }}
    /^\[/ && skip_anyrouter == 1 {{ skip_anyrouter = 0 }}
    skip_anyrouter == 1 {{ next }}
    /^\[/ {{
      if (!seen_section) emit_missing_root()
      seen_section = 1
    }}
    !seen_section && /^model[[:space:]]*=/ {{ print "model = \"" model "\""; wrote_model = 1; next }}
    !seen_section && /^model_provider[[:space:]]*=/ {{ print "model_provider = \"" provider "\""; wrote_provider = 1; next }}
    !seen_section && /^preferred_auth_method[[:space:]]*=/ {{ print "preferred_auth_method = \"apikey\""; wrote_auth = 1; next }}
    !seen_section && /^approval_policy[[:space:]]*=/ {{ print "approval_policy = \"never\""; wrote_approval = 1; next }}
    !seen_section && /^sandbox_mode[[:space:]]*=/ {{ print "sandbox_mode = \"danger-full-access\""; wrote_sandbox = 1; next }}
    {{ print }}
    END {{
      if (!seen_section) emit_missing_root()
      print ""
      print "[model_providers.anyrouter]"
      print "name = \"Any Router\""
      print "base_url = \"" base_url "\""
      print "wire_api = \"responses\""
    }}
  ' "$CODEX_CONFIG_FILE" > "${{CODEX_CONFIG_FILE}}.new"
  mv "${{CODEX_CONFIG_FILE}}.new" "$CODEX_CONFIG_FILE"
}}

write_claude_settings() {{
  local python_bin

  mkdir -p "$CLAUDE_DIR"
  if [[ -f "$CLAUDE_SETTINGS_FILE" ]]; then
    backup_file "$CLAUDE_SETTINGS_FILE"
  fi

  python_bin="$(command -v python3 || command -v python || true)"
  if [[ -z "$python_bin" ]]; then
    printf 'ERROR: python3 or python is required to update %s\n' "$CLAUDE_SETTINGS_FILE" >&2
    return 1
  fi

  "$python_bin" - "$CLAUDE_SETTINGS_FILE" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
try:
    data = json.loads(path.read_text(encoding='utf-8')) if path.is_file() else {{}}
except json.JSONDecodeError:
    data = {{}}

if not isinstance(data, dict):
    data = {{}}

permissions = data.get('permissions')
if not isinstance(permissions, dict):
    permissions = {{}}

permissions['defaultMode'] = 'bypassPermissions'
data['permissions'] = permissions
path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
PY
}}

main() {{
  mkdir -p "$STATE_DIR" "$CLAUDE_DIR" "$CODEX_DIR"
  ensure_clients

  backup_file "$ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Active account: ${{ACTIVE_ACCOUNT_NAME}}
export ANTHROPIC_AUTH_TOKEN="${{ANYROUTER_AUTH_TOKEN}}"
export ANTHROPIC_BASE_URL="${{ANYROUTER_BASE_URL}}"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
export CLAUDE_CODE_ATTRIBUTION_HEADER=0
EOF
  if [[ "$NEEDS_NPM_USER_PATH" == "1" ]]; then
    printf 'export PATH="%s/bin:${{PATH}}"\n' "$NPM_USER_PREFIX" >> "$ENV_FILE"
  fi

  backup_file "$ACTIVE_FILE"
  cat > "$ACTIVE_FILE" <<EOF
{{
  "index": ${{ACTIVE_ACCOUNT_INDEX}},
  "name": "$(json_escape "$ACTIVE_ACCOUNT_NAME")"
}}
EOF

  backup_file "$CODEX_AUTH_FILE"
  cat > "$CODEX_AUTH_FILE" <<EOF
{{
  "OPENAI_API_KEY": "${{ANYROUTER_AUTH_TOKEN}}"
}}
EOF

  write_claude_settings
  chmod 600 "$CODEX_AUTH_FILE" "$ENV_FILE" "$ACTIVE_FILE" "$CLAUDE_SETTINGS_FILE" 2>/dev/null || true
  write_codex_config
  ensure_shell_hook "${{HOME}}/.zshrc"
  ensure_shell_hook "${{HOME}}/.bashrc"

  printf '\nAnyRouter deploy complete.\n'
  printf 'Active account: %s\n' "$ACTIVE_ACCOUNT_NAME"
  printf 'Claude Code env: %s\n' "$ENV_FILE"
  printf 'Claude Code settings: %s\n' "$CLAUDE_SETTINGS_FILE"
  printf 'Codex auth: %s\n' "$CODEX_AUTH_FILE"
  printf 'Codex config: %s\n' "$CODEX_CONFIG_FILE"
  printf 'Claude Code client: %s\n' "$(command -v claude)"
  printf 'Codex client: %s\n' "$(command -v codex)"
  printf '\nRun this in the current shell to apply immediately:\n'
  printf '  source "%s"\n\n' "$ENV_FILE"
}}

main "$@"
"""


@dataclass
class AccountBalance:
	index: int
	name: str
	provider: str
	quota: float | None
	used_quota: float | None
	error: str | None = None
	is_active: bool = False
	has_auth_token: bool = False

	@property
	def quota_ok(self) -> bool:
		return self.quota is not None


def format_balance_error(error: str | None) -> str:
	if not error:
		return '未知错误'

	normalized = error.strip()
	upper = normalized.upper()

	if 'HTTP 401' in upper:
		if '不匹配' in normalized or 'MISMATCH' in upper:
			return 'api_user 不匹配'
		return 'Cookie 过期'
	if 'HTTP 403' in upper:
		return '访问被拒绝'
	if 'HTTP 404' in upper:
		return '接口不存在'
	if 'HTTP 5' in upper or 'HTTP 50' in upper:
		match = re.search(r'HTTP (\d+)', normalized, re.IGNORECASE)
		return f'HTTP {match.group(1)}' if match else '服务异常'
	if 'WAF' in upper:
		return 'WAF 失败'
	if 'INVALID COOKIES' in upper:
		return 'Cookie 无效'
	if 'TIMEOUT' in upper or 'TIMED OUT' in upper:
		return '请求超时'

	match = re.search(r'HTTP (\d+)', normalized, re.IGNORECASE)
	if match:
		code = match.group(1)
		if code == '401':
			return 'Cookie 过期'
		return f'HTTP {code}'

	if len(normalized) <= 16:
		return normalized
	return f'{normalized[:14]}…'


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description='List balances and switch AnyRouter accounts locally.')
	parser.add_argument(
		'-f',
		'--file',
		type=Path,
		default=None,
		help=(
			'Accounts JSON file. Defaults to ANYROUTER_ACCOUNTS_FILE, '
			f'./{DEFAULT_ACCOUNTS_FILE_NAME}, {CONFIG_ACCOUNTS_FILE}, then project ./{DEFAULT_ACCOUNTS_FILE_NAME}.'
		),
	)
	parser.add_argument(
		'--plain',
		action='store_true',
		help='Plain text output (for scripting)',
	)
	subparsers = parser.add_subparsers(dest='command')

	subparsers.add_parser('list', help='List accounts and balances')
	subparsers.add_parser('current', help='Show active account')
	subparsers.add_parser('apply', help='Re-apply the active account without switching')

	switch_parser = subparsers.add_parser('switch', help='Switch to an account by index')
	switch_parser.add_argument('index', type=int, nargs='?', help='Account index (1-based)')

	subparsers.add_parser('env', help='Print shell exports for the active account')
	subparsers.add_parser('interactive', help='Interactive account switcher (default)')

	list_parser = subparsers.add_parser('refresh', help='Alias for list')
	list_parser.set_defaults(command='list')

	return parser.parse_args()


def resolve_accounts_file(path: Path | None) -> Path:
	if path is not None:
		return path.expanduser()

	env_path = os.environ.get('ANYROUTER_ACCOUNTS_FILE')
	if env_path:
		return Path(env_path).expanduser()

	candidates = [
		Path.cwd() / DEFAULT_ACCOUNTS_FILE_NAME,
		CONFIG_ACCOUNTS_FILE,
		PROJECT_ROOT / DEFAULT_ACCOUNTS_FILE_NAME,
	]
	for candidate in candidates:
		if candidate.is_file():
			return candidate

	return CONFIG_ACCOUNTS_FILE


def load_accounts(path: Path) -> list[dict[str, Any]]:
	accounts = load_accounts_file(path)
	refresh_api_users(accounts)
	return accounts


def load_active_state() -> dict[str, Any] | None:
	if not ACTIVE_STATE_FILE.is_file():
		return None
	try:
		return json.loads(ACTIVE_STATE_FILE.read_text(encoding='utf-8'))
	except json.JSONDecodeError:
		return None


def save_active_state(index: int, name: str) -> None:
	STATE_DIR.mkdir(parents=True, exist_ok=True)
	payload = {'index': index, 'name': name}
	ACTIVE_STATE_FILE.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def resolve_base_url(provider_name: str, app_config: AppConfig) -> str:
	# provider = app_config.get_provider(provider_name)
	# if provider is None:
	return DEFAULT_BASE_URL.rstrip('/')
	# return provider.domain.rstrip('/')


def get_auth_token(account: dict[str, Any]) -> str:
	token = account.get('auth_token')
	if not isinstance(token, str) or not token.strip():
		raise ValueError(f'Account "{account.get("name", "unknown")}" missing auth_token')
	return token.strip()


@contextlib.contextmanager
def suppress_checkin_logs():
	buffer = io.StringIO()
	with contextlib.redirect_stdout(buffer), contextlib.redirect_stderr(buffer):
		yield


async def fetch_account_balance(
	account: dict[str, Any],
	index: int,
	app_config: AppConfig,
	active_index: int | None,
) -> AccountBalance:
	name = account.get('name') or f'Account {index + 1}'
	provider_name = account.get('provider', 'anyrouter')
	has_auth_token = bool(str(account.get('auth_token', '')).strip())

	try:
		account_cfg = AccountConfig.from_dict(account, index)
	except Exception as exc:
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error=str(exc),
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)

	provider_config = app_config.get_provider(account_cfg.provider)
	if provider_config is None:
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error=f'Unknown provider: {provider_name}',
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)

	user_cookies = parse_cookies(account_cfg.cookies)
	if not user_cookies:
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error='Invalid cookies',
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)

	try:
		with suppress_checkin_logs():
			all_cookies = await prepare_cookies(name, provider_config, user_cookies, headless=True)
	except RuntimeError as exc:
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error=str(exc).split('\n')[0],
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)
	if not all_cookies:
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error='Failed to get WAF cookies',
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)

	client = httpx.Client(http2=True, timeout=30.0)
	try:
		client.cookies.update(all_cookies)
		headers = {
			'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36',
			'Accept': 'application/json, text/plain, */*',
			'Referer': provider_config.domain,
			'Origin': provider_config.domain,
			provider_config.api_user_key: account_cfg.api_user,
		}
		user_info_url = f'{provider_config.domain}{provider_config.user_info_path}'
		with suppress_checkin_logs():
			user_info = get_user_info(client, headers, user_info_url)
	except Exception as exc:
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error=str(exc)[:60],
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)
	finally:
		client.close()

	if not user_info.get('success'):
		return AccountBalance(
			index=index,
			name=name,
			provider=provider_name,
			quota=None,
			used_quota=None,
			error=user_info.get('error', 'Failed to fetch balance'),
			is_active=index == active_index,
			has_auth_token=has_auth_token,
		)

	return AccountBalance(
		index=index,
		name=name,
		provider=provider_name,
		quota=user_info['quota'],
		used_quota=user_info['used_quota'],
		is_active=index == active_index,
		has_auth_token=has_auth_token,
	)


async def fetch_all_balances(
	accounts: list[dict[str, Any]],
	active_index: int | None,
	*,
	plain: bool = False,
) -> list[AccountBalance]:
	app_config = AppConfig.load_from_env()
	results: list[AccountBalance] = []

	if plain:
		for index, account in enumerate(accounts):
			label = account.get('name') or f'Account {index + 1}'
			print(f'[INFO] Fetching balance for {label}...')
			results.append(await fetch_account_balance(account, index, app_config, active_index))
		return results

	with Progress(
		SpinnerColumn(style='cyan'),
		TextColumn('[bold cyan]{task.description}'),
		console=console,
		transient=True,
	) as progress:
		for index, account in enumerate(accounts):
			label = account.get('name') or f'Account {index + 1}'
			task = progress.add_task(f'正在查询 {label} 余额...', total=None)
			results.append(await fetch_account_balance(account, index, app_config, active_index))
			progress.remove_task(task)

	return results


def render_header() -> None:
	console.print()
	console.print(
		Panel(
			Text.from_markup(
				'[bold white]AnyRouter 账号切换[/]\n'
				'[dim]Claude Code · Codex · 本地 auth_token 管理[/]'
			),
			border_style='bright_blue',
			padding=(1, 2),
		)
	)


def render_account_table(balances: list[AccountBalance]) -> None:
	table = Table(
		title='账号列表',
		box=box.ROUNDED,
		border_style='bright_black',
		header_style='bold cyan',
		title_style='bold white',
		show_lines=False,
		padding=(0, 1),
	)
	table.add_column('#', justify='right', style='dim', width=3)
	table.add_column('名称', style='bold', min_width=16)
	table.add_column('余额', justify='right', min_width=10)
	table.add_column('已用', justify='right', min_width=10)
	table.add_column('状态', min_width=10)
	table.add_column('平台', style='dim')
	table.add_column('Token', justify='center', width=6)
	table.add_column('当前', justify='center', width=4)

	failed: list[AccountBalance] = []
	for item in balances:
		if item.quota_ok:
			quota_cell = Text(f'${item.quota:.2f}', style='bold green')
			used_cell = Text(f'${item.used_quota:.2f}', style='yellow')
			status_cell = Text('正常', style='green')
		else:
			quota_cell = Text('-', style='dim')
			used_cell = Text('-', style='dim')
			status_cell = Text(format_balance_error(item.error), style='bold red')
			failed.append(item)

		token_cell = Text('✓', style='green') if item.has_auth_token else Text('✗', style='red')
		current_cell = Text('●', style='bold green') if item.is_active else Text('', style='dim')
		name_style = 'bold white on dark_green' if item.is_active else 'white'

		table.add_row(
			str(item.index + 1),
			Text(item.name, style=name_style),
			quota_cell,
			used_cell,
			status_cell,
			item.provider,
			token_cell,
			current_cell,
		)

	console.print(table)

	if failed:
		details = '\n'.join(
			f'[bold white]{item.name}[/]: [red]{item.error or "未知错误"}[/]' for item in failed
		)
		console.print(
			Panel(
				details
				+ '\n\n[dim]Cookie 过期：更新 session。\n'
				'api_user 不匹配：重新运行 anyrouter-accounts 会自动修正，再 push 同步到 GitHub。[/]',
				title='余额查询失败',
				border_style='red',
				padding=(1, 2),
			)
		)

	console.print()


def print_account_table_plain(balances: list[AccountBalance]) -> None:
	name_width = max(len(item.name) for item in balances)
	name_width = max(name_width, len('名称'))
	print()
	print(f' {"#":>2}  {"名称":<{name_width}}  {"余额":>10}  {"已用":>10}  {"状态":<12}  {"平台":<12}  Token  当前')
	print(f' {"-" * 2}  {"-" * name_width}  {"-" * 10}  {"-" * 10}  {"-" * 12}  {"-" * 12}  -----  ----')
	failed: list[AccountBalance] = []
	for item in balances:
		if item.quota_ok:
			quota = f'${item.quota:.2f}'
			used = f'${item.used_quota:.2f}'
			status = '正常'
		else:
			quota = '-'
			used = '-'
			status = format_balance_error(item.error)
			failed.append(item)
		current = '✓' if item.is_active else ''
		token_flag = 'yes' if item.has_auth_token else 'no'
		print(
			f' {item.index + 1:>2}  {item.name:<{name_width}}  {quota:>10}  '
			f'{used:>10}  {status:<12}  {item.provider:<12}  {token_flag:<5}  {current}'
		)
	if failed:
		print()
		print('余额查询失败:')
		for item in failed:
			print(f'  - {item.name}: {item.error or "未知错误"}')
	print()


def ensure_codex_config(base_url: str) -> None:
	CODEX_DIR.mkdir(parents=True, exist_ok=True)
	v1_url = f'{base_url.rstrip("/")}/v1'

	if not CODEX_CONFIG_FILE.is_file():
		CODEX_CONFIG_FILE.write_text(CODEX_CONFIG_TEMPLATE.format(base_url=base_url.rstrip('/')), encoding='utf-8')
		return

	content = CODEX_CONFIG_FILE.read_text(encoding='utf-8')
	updated = upsert_toml_root_string(content, 'approval_policy', 'never')
	updated = upsert_toml_root_string(updated, 'sandbox_mode', 'danger-full-access')
	updated = re.sub(r'base_url\s*=\s*"[^"]*"', f'base_url = "{v1_url}"', updated, count=1)
	if updated != content:
		CODEX_CONFIG_FILE.write_text(updated, encoding='utf-8')


def upsert_toml_root_string(content: str, key: str, value: str) -> str:
	line = f'{key} = "{value}"'
	pattern = rf'^{re.escape(key)}\s*=\s*"[^"]*"'
	if re.search(pattern, content, re.MULTILINE):
		return re.sub(pattern, line, content, count=1, flags=re.MULTILINE)

	section_match = re.search(r'^\[', content, re.MULTILINE)
	insert = f'{line}\n'
	if section_match:
		return content[: section_match.start()] + insert + content[section_match.start() :]
	trailing_newline = '' if content.endswith('\n') or not content else '\n'
	return f'{content}{trailing_newline}{insert}'


def ensure_claude_settings() -> None:
	CLAUDE_DIR.mkdir(parents=True, exist_ok=True)
	data: Any = {}
	if CLAUDE_SETTINGS_FILE.is_file():
		try:
			data = json.loads(CLAUDE_SETTINGS_FILE.read_text(encoding='utf-8'))
		except json.JSONDecodeError:
			data = {}

	if not isinstance(data, dict):
		data = {}

	permissions = data.get('permissions')
	if not isinstance(permissions, dict):
		permissions = {}

	permissions['defaultMode'] = 'bypassPermissions'
	data['permissions'] = permissions
	CLAUDE_SETTINGS_FILE.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')


def read_codex_string_setting(key: str, default: str) -> str:
	if not CODEX_CONFIG_FILE.is_file():
		return default

	content = CODEX_CONFIG_FILE.read_text(encoding='utf-8')
	match = re.search(rf'^{re.escape(key)}\s*=\s*"([^"]*)"', content, re.MULTILINE)
	if match:
		return match.group(1)
	return default


def write_deploy_script(account: dict[str, Any], index: int, base_url: str, name: str) -> Path:
	auth_token = get_auth_token(account)
	codex_model = read_codex_string_setting('model', 'gpt-5.5')
	codex_provider = read_codex_string_setting('model_provider', 'anyrouter')
	content = DEPLOY_SCRIPT_TEMPLATE.format(
		account_name=shlex.quote(name),
		account_index=shlex.quote(str(index)),
		auth_token=shlex.quote(auth_token),
		base_url=shlex.quote(base_url.rstrip('/')),
		codex_model=shlex.quote(codex_model),
		codex_provider=shlex.quote(codex_provider),
	)

	DEPLOY_SCRIPT_FILE.parent.mkdir(parents=True, exist_ok=True)
	DEPLOY_SCRIPT_FILE.write_text(content, encoding='utf-8')
	DEPLOY_SCRIPT_FILE.chmod(0o700)
	return DEPLOY_SCRIPT_FILE


def sync_zshrc_hook() -> list[str]:
	"""Ensure ~/.zshrc sources env.sh and remove conflicting Claude exports."""
	actions: list[str] = []
	lines: list[str] = []
	if ZSHRC_FILE.is_file():
		lines = ZSHRC_FILE.read_text(encoding='utf-8').splitlines()

	cleaned: list[str] = []
	skip_block = False
	for line in lines:
		stripped = line.strip()
		if stripped == ZSHRC_HOOK_START:
			skip_block = True
			if 'removed old hook block' not in actions:
				actions.append('removed old hook block')
			continue
		if stripped == ZSHRC_HOOK_END:
			skip_block = False
			continue
		if skip_block:
			continue

		if stripped.startswith('export =export'):
			actions.append(f'removed broken export: {stripped}')
			continue
		if (
			stripped.startswith('export ANTHROPIC_AUTH_TOKEN=')
			or stripped.startswith('export ANTHROPIC_BASE_URL=')
			or stripped.startswith('export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=')
			or stripped.startswith('export CLAUDE_CODE_ATTRIBUTION_HEADER=')
		):
			actions.append(f'removed conflicting export: {stripped}')
			continue

		cleaned.append(line)

	while cleaned and not cleaned[-1].strip():
		cleaned.pop()

	cleaned.extend(
		[
			'',
			ZSHRC_HOOK_START,
			'# Managed by anyrouter-accounts',
			f'[[ -f "{ENV_EXPORT_FILE}" ]] && source "{ENV_EXPORT_FILE}"',
			ZSHRC_HOOK_END,
			'',
		]
	)
	ZSHRC_FILE.write_text('\n'.join(cleaned), encoding='utf-8')
	actions.append(f'updated {ZSHRC_FILE}')
	return actions


def apply_account(account: dict[str, Any], index: int, app_config: AppConfig) -> tuple[str, list[str], Path]:
	auth_token = get_auth_token(account)
	provider_name = account.get('provider', 'anyrouter')
	base_url = resolve_base_url(provider_name, app_config)
	name = account.get('name') or f'Account {index + 1}'

	STATE_DIR.mkdir(parents=True, exist_ok=True)
	env_content = (
		f'# Active account: {name}\n'
		f'export ANTHROPIC_AUTH_TOKEN="{auth_token}"\n'
		f'export ANTHROPIC_BASE_URL="{base_url}"\n'
		'export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1\n'
		'export CLAUDE_CODE_ATTRIBUTION_HEADER=0\n'
	)
	ENV_EXPORT_FILE.write_text(env_content, encoding='utf-8')

	ensure_claude_settings()
	ensure_codex_config(base_url)
	CODEX_AUTH_FILE.write_text(json.dumps({'OPENAI_API_KEY': auth_token}, indent=2) + '\n', encoding='utf-8')
	save_active_state(index, name)
	zshrc_actions = sync_zshrc_hook()
	deploy_script = write_deploy_script(account, index, base_url, name)
	return name, zshrc_actions, deploy_script


def render_apply_result(name: str, deploy_script: Path, zshrc_actions: list[str] | None = None) -> None:
	zshrc_note = ''
	if zshrc_actions:
		zshrc_note = '\n[dim]~/.zshrc[/] 已同步（source env.sh，已清理冲突的 Claude 变量）\n'

	body = (
		f'[bold green]✓[/] 已切换至 [bold white]{name}[/]\n\n'
		f'[dim]Claude Code[/]  [cyan]{ENV_EXPORT_FILE}[/]\n'
		f'[dim]Claude perm[/]  [cyan]{CLAUDE_SETTINGS_FILE}[/]\n'
		f'[dim]Codex[/]         [cyan]{CODEX_AUTH_FILE}[/]\n'
		f'[dim]Deploy[/]        [cyan]{deploy_script}[/]\n'
		f'{zshrc_note}\n'
		f'[bold]当前终端立即生效：[/]\n'
		f'  [yellow]source {ENV_EXPORT_FILE}[/]\n\n'
		f'[dim]新开终端会自动加载；deploy 脚本已按当前账号重新生成[/]'
	)
	console.print(Panel(body, title='切换成功', border_style='green', padding=(1, 2)))


def print_apply_result_plain(name: str, deploy_script: Path, zshrc_actions: list[str] | None = None) -> None:
	print()
	print(f'已切换至: {name}')
	print(f'已更新: {ENV_EXPORT_FILE}')
	print(f'已更新: {CLAUDE_SETTINGS_FILE}')
	print(f'已更新: {CODEX_AUTH_FILE}')
	print(f'已生成 deploy: {deploy_script}')
	if zshrc_actions:
		print('已同步 ~/.zshrc')
		for action in zshrc_actions:
			print(f'  - {action}')
	print()
	print('当前终端立即生效:')
	print(f'  source {ENV_EXPORT_FILE}')


async def cmd_list(accounts: list[dict[str, Any]], *, plain: bool = False) -> None:
	active = load_active_state()
	active_index = active['index'] if active and isinstance(active.get('index'), int) else None
	if not plain:
		render_header()
	balances = await fetch_all_balances(accounts, active_index, plain=plain)
	if plain:
		print_account_table_plain(balances)
	else:
		render_account_table(balances)


def cmd_current(accounts: list[dict[str, Any]], *, plain: bool = False) -> None:
	active = load_active_state()
	if not active:
		message = '当前没有激活账号，运行 anyrouter-accounts 进行切换。'
		if plain:
			print(message)
		else:
			console.print(Panel(message, title='当前账号', border_style='yellow'))
		return

	index = active.get('index')
	name = active.get('name', 'unknown')
	if isinstance(index, int) and 0 <= index < len(accounts):
		account = accounts[index]
		token = account.get('auth_token', '')
		masked = f'{token[:7]}...{token[-4:]}' if len(token) > 11 else '(missing)'
		if plain:
			print(f'当前账号: {name} (#{index + 1})')
			print(f'auth_token: {masked}')
			print(f'Claude env: {ENV_EXPORT_FILE}')
			print(f'Codex auth: {CODEX_AUTH_FILE}')
			return

		body = (
			f'[bold white]{name}[/]  [dim](#{index + 1})[/]\n\n'
			f'[dim]auth_token[/]  {masked}\n'
			f'[dim]Claude[/]      [cyan]{ENV_EXPORT_FILE}[/]\n'
			f'[dim]Codex[/]       [cyan]{CODEX_AUTH_FILE}[/]'
		)
		console.print(Panel(body, title='当前账号', border_style='bright_blue', padding=(1, 2)))
	else:
		message = f'当前记录: {name} (#{index})'
		if plain:
			print(message)
		else:
			console.print(Panel(message, title='当前账号', border_style='yellow'))


def cmd_env(accounts: list[dict[str, Any]]) -> int:
	active = load_active_state()
	if not active or not isinstance(active.get('index'), int):
		print('No active account selected.', file=sys.stderr)
		return 1

	index = active['index']
	if index < 0 or index >= len(accounts):
		print('Active account index is out of range.', file=sys.stderr)
		return 1

	account = accounts[index]
	app_config = AppConfig.load_from_env()
	auth_token = get_auth_token(account)
	base_url = resolve_base_url(account.get('provider', 'anyrouter'), app_config)
	print(f'export ANTHROPIC_AUTH_TOKEN="{auth_token}"')
	print(f'export ANTHROPIC_BASE_URL="{base_url}"')
	print('export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1')
	print('export CLAUDE_CODE_ATTRIBUTION_HEADER=0')
	return 0


async def cmd_switch(accounts: list[dict[str, Any]], index: int | None, *, plain: bool = False) -> int:
	app_config = AppConfig.load_from_env()
	active = load_active_state()
	active_index = active['index'] if active and isinstance(active.get('index'), int) else None

	if index is None:
		if not plain:
			render_header()
		balances = await fetch_all_balances(accounts, active_index, plain=plain)
		if plain:
			print_account_table_plain(balances)
		else:
			render_account_table(balances)

		if plain:
			while True:
				choice = input(f'选择账号 [1-{len(accounts)}]，或 q 退出: ').strip().lower()
				if choice in {'q', 'quit', 'exit'}:
					return 0
				if choice.isdigit():
					selected = int(choice)
					if 1 <= selected <= len(accounts):
						index = selected
						break
				print('输入无效，请重试。')
		else:
			console.print(f'[dim]输入编号 [1-{len(accounts)}] 切换账号，输入 q 退出[/]')
			while True:
				choice = Prompt.ask(
					'[bold cyan]选择要切换的账号[/]',
					default='q',
					show_default=False,
				).strip().lower()
				if choice in {'q', 'quit', 'exit', ''}:
					console.print('[dim]已退出[/]')
					return 0
				if choice.isdigit():
					selected = int(choice)
					if 1 <= selected <= len(accounts):
						index = selected
						break
				error_console.print('[red]输入无效，请输入账号编号或 q[/]')
	else:
		if index < 1 or index > len(accounts):
			message = f'index must be between 1 and {len(accounts)}'
			if plain:
				print(f'ERROR: {message}', file=sys.stderr)
			else:
				error_console.print(f'[bold red]ERROR:[/] {message}')
			return 1

	account = accounts[index - 1]
	try:
		name, zshrc_actions, deploy_script = apply_account(account, index - 1, app_config)
	except ValueError as exc:
		if plain:
			print(f'ERROR: {exc}', file=sys.stderr)
		else:
			error_console.print(Panel(str(exc), title='切换失败', border_style='red'))
		return 1

	if plain:
		print_apply_result_plain(name, deploy_script, zshrc_actions)
	else:
		render_apply_result(name, deploy_script, zshrc_actions)
	return 0


async def async_main() -> int:
	args = parse_args()
	command = args.command or 'interactive'
	plain = args.plain or command == 'env'
	accounts_file = resolve_accounts_file(args.file)

	try:
		accounts = load_accounts(accounts_file)
	except (FileNotFoundError, ValueError) as exc:
		if plain:
			print(f'ERROR: {exc}', file=sys.stderr)
		else:
			error_console.print(f'[bold red]ERROR:[/] {exc}')
			error_console.print(
				f'[dim]请将账号文件放到当前目录 ./{DEFAULT_ACCOUNTS_FILE_NAME}，'
				f'或 {CONFIG_ACCOUNTS_FILE}，也可以用 -f 指定。[/]'
			)
		return 1

	if not accounts:
		message = 'no accounts found'
		if plain:
			print(f'ERROR: {message}', file=sys.stderr)
		else:
			error_console.print(f'[bold red]ERROR:[/] {message}')
		return 1

	if command == 'list':
		await cmd_list(accounts, plain=plain)
		return 0

	if command == 'current':
		cmd_current(accounts, plain=plain)
		return 0

	if command == 'env':
		return cmd_env(accounts)

	if command == 'apply':
		active = load_active_state()
		if not active or not isinstance(active.get('index'), int):
			error_console.print('[bold red]ERROR:[/] no active account to apply')
			return 1
		index = active['index']
		if index < 0 or index >= len(accounts):
			error_console.print('[bold red]ERROR:[/] active account index is out of range')
			return 1
		try:
			name, zshrc_actions, deploy_script = apply_account(accounts[index], index, AppConfig.load_from_env())
		except ValueError as exc:
			error_console.print(f'[bold red]ERROR:[/] {exc}')
			return 1
		if plain:
			print_apply_result_plain(name, deploy_script, zshrc_actions)
		else:
			render_apply_result(name, deploy_script, zshrc_actions)
		return 0

	if command in {'switch', 'interactive'}:
		selected_index = args.index if command == 'switch' else None
		return await cmd_switch(accounts, selected_index, plain=plain)

	message = f'unknown command: {command}'
	if plain:
		print(f'ERROR: {message}', file=sys.stderr)
	else:
		error_console.print(f'[bold red]ERROR:[/] {message}')
	return 1


def main() -> int:
	try:
		return asyncio.run(async_main())
	except KeyboardInterrupt:
		console.print('\n[dim]已取消[/]')
		return 130


if __name__ == '__main__':
	raise SystemExit(main())
