#!/usr/bin/env python3
"""
Generate a portable Claude Code / Codex setup script backed by local cc-switch proxy.

The generated bash script installs Claude Code and Codex, then writes the local
Claude/Codex config files with the local HTTP proxy entry point replaced by the
public lyf-expose URL.
"""

from __future__ import annotations

import argparse
import base64
import re
import shlex
import socket
import sys
import textwrap
import time
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

from rich.console import Console
from rich.panel import Panel

console = Console()
error_console = Console(stderr=True)

DEFAULT_OUTPUT_FILE = Path.home() / 'Downloads' / 'setup_cc_codex.bash'
DEFAULT_PROXY_HOST = '127.0.0.1'
LOCAL_HTTP_URL_RE = re.compile(
	r'http://(?P<host>127\.0\.0\.1|localhost|0\.0\.0\.0|\[::1\])'
	r'(?::(?P<port>\d{1,5}))?'
	r'(?P<suffix>[^"\'\s<>)\]]*)'
)


@dataclass(frozen=True)
class ConfigSpec:
	label: str
	source: Path
	target_rel: str
	mode: str = '600'
	required: bool = True


@dataclass(frozen=True)
class ConfigPayload:
	spec: ConfigSpec
	content: str
	replacements: int


DEFAULT_CONFIG_SPECS = [
	ConfigSpec(
		'Claude Code settings',
		Path.home() / '.claude' / 'settings.json',
		'.claude/settings.json',
		required=False,
	),
	ConfigSpec('Codex auth', Path.home() / '.codex' / 'auth.json', '.codex/auth.json', required=False),
	ConfigSpec('Codex config', Path.home() / '.codex' / 'config.toml', '.codex/config.toml', required=False),
]

OPTIONAL_CONFIG_SPECS = {
	'claude-json': ConfigSpec('Claude Code global state', Path.home() / '.claude.json', '.claude.json', '600', False),
	'env-sh': ConfigSpec(
		'AnyRouter shell env',
		Path.home() / '.config' / 'anyrouter-check-in' / 'env.sh',
		'.config/anyrouter-check-in/env.sh',
		'600',
		False,
	),
}

SETUP_SCRIPT_HEADER = r"""#!/usr/bin/env bash
set -euo pipefail

# Generated by setup_cc_proxy.py.
# Keep the local setup_cc_proxy.py / lyf-expose process running while remote
# machines or containers use this proxy URL.

PUBLIC_PROXY_URL={public_proxy_url}
LOCAL_PROXY_PORT={local_proxy_port}
NPM_USER_PREFIX="${{NPM_CONFIG_PREFIX:-${{HOME}}/.npm-global}}"
NEEDS_NPM_USER_PATH=0

backup_file() {{
  local path="$1"
  if [[ -f "$path" ]]; then
    cp "$path" "${{path}}.bak.$(date +%Y%m%d%H%M%S)"
  fi
}}

run_apt_get() {{
  if [[ "${{EUID:-$(id -u)}}" -eq 0 ]]; then
    apt-get "$@"
    return
  fi

  if command -v sudo >/dev/null 2>&1; then
    sudo apt-get "$@"
    return
  fi

  printf 'ERROR: apt-get requires root or sudo.\n' >&2
  return 1
}}

install_npm_with_apt() {{
  if [[ "$(uname -s)" != "Linux" ]]; then
    return 1
  fi

  if ! command -v apt-get >/dev/null 2>&1; then
    return 1
  fi

  printf 'npm not found; installing via apt...\n'
  if ! run_apt_get update -qq; then
    return 1
  fi

  DEBIAN_FRONTEND=noninteractive run_apt_get install -y npm
}}

ensure_npm_available() {{
  if command -v npm >/dev/null 2>&1; then
    return 0
  fi

  if install_npm_with_apt && command -v npm >/dev/null 2>&1; then
    printf 'npm installed: %s\n' "$(command -v npm)"
    return 0
  fi

  printf 'ERROR: npm is required to install missing Claude Code/Codex clients.\n' >&2
  printf 'Install Node.js/npm first, then rerun this setup script.\n' >&2
  return 1
}}

prepend_path_once() {{
  local dir="$1"
  case ":$PATH:" in
    *":$dir:"*) ;;
    *) export PATH="$dir:$PATH" ;;
  esac
}}

npm_global_prefix() {{
  npm config get prefix 2>/dev/null | tr -d '\r\n' || printf '/usr/local'
}}

npm_global_prefix_writable() {{
  local prefix
  prefix="$(npm_global_prefix)"
  [[ -n "$prefix" ]] || return 1
  if [[ -w "$prefix" ]]; then
    return 0
  fi
  if [[ ! -e "$prefix" ]] && [[ -w "$(dirname "$prefix")" ]]; then
    return 0
  fi
  return 1
}}

install_npm_cli_to_user_prefix() {{
  local package="$1"

  mkdir -p "$NPM_USER_PREFIX"
  NPM_CONFIG_PREFIX="$NPM_USER_PREFIX" npm install -g "$package"
  prepend_path_once "$NPM_USER_PREFIX/bin"
  NEEDS_NPM_USER_PATH=1
}}

install_npm_cli() {{
  local label="$1"
  local binary="$2"
  local package="$3"

  if command -v "$binary" >/dev/null 2>&1; then
    printf '%s found: %s\n' "$label" "$(command -v "$binary")"
    return 0
  fi

  ensure_npm_available
  printf '%s not found; installing %s...\n' "$label" "$package"

  if npm_global_prefix_writable; then
    npm install -g "$package" || true
    hash -r 2>/dev/null || true
  else
    printf 'System npm prefix %s is not writable; using %s\n' "$(npm_global_prefix)" "$NPM_USER_PREFIX"
    install_npm_cli_to_user_prefix "$package"
    hash -r 2>/dev/null || true
  fi

  if command -v "$binary" >/dev/null 2>&1; then
    printf '%s installed: %s\n' "$label" "$(command -v "$binary")"
    return 0
  fi

  if [[ "$NEEDS_NPM_USER_PATH" != "1" ]]; then
    printf 'Global npm install did not expose %s; retrying with user prefix %s...\n' "$binary" "$NPM_USER_PREFIX"
    install_npm_cli_to_user_prefix "$package"
    hash -r 2>/dev/null || true
  fi

  if ! command -v "$binary" >/dev/null 2>&1; then
    printf 'ERROR: %s installation finished but %s is still not on PATH.\n' "$label" "$binary" >&2
    printf 'Expected binary under %s/bin. Check npm output above.\n' "$NPM_USER_PREFIX" >&2
    return 1
  fi

  printf '%s installed: %s\n' "$label" "$(command -v "$binary")"
}}

ensure_clients() {{
  install_npm_cli 'Claude Code' 'claude' '@anthropic-ai/claude-code'
  install_npm_cli 'Codex CLI' 'codex' '@openai/codex'
}}

base64_decode() {{
  if base64 --decode </dev/null >/dev/null 2>&1; then
    base64 --decode
    return
  fi
  if base64 -D </dev/null >/dev/null 2>&1; then
    base64 -D
    return
  fi

  printf 'ERROR: base64 decode is unavailable.\n' >&2
  return 1
}}

write_config_file() {{
  local target="$1"
  local mode="$2"
  local label="$3"
  local tmp_file

  mkdir -p "$(dirname "$target")"
  backup_file "$target"
  tmp_file="$(mktemp)"
  if ! base64_decode > "$tmp_file"; then
    rm -f "$tmp_file"
    return 1
  fi

  mv "$tmp_file" "$target"
  chmod "$mode" "$target" 2>/dev/null || true
  printf '%s: %s\n' "$label" "$target"
}}

ensure_user_path_hook() {{
  local rc_file="$1"
  local hook_line

  if [[ "$NEEDS_NPM_USER_PATH" != "1" ]]; then
    return 0
  fi

  hook_line="export PATH=\"${{NPM_USER_PREFIX}}/bin:\$PATH\""
  mkdir -p "$(dirname "$rc_file")"
  touch "$rc_file"
  if grep -F "${{NPM_USER_PREFIX}}/bin" "$rc_file" >/dev/null 2>&1; then
    return 0
  fi

  backup_file "$rc_file"
  {{
    printf '\n# Added by setup_cc_codex.bash\n'
    printf '%s\n' "$hook_line"
  }} >> "$rc_file"
}}

ensure_ssl_cert_file_hook() {{
  local rc_file="$1"
  local hook_line='export SSL_CERT_FILE=/usr/lib/ssl/cert.pem'

  mkdir -p "$(dirname "$rc_file")"
  touch "$rc_file"
  if grep -F 'SSL_CERT_FILE=/usr/lib/ssl/cert.pem' "$rc_file" >/dev/null 2>&1; then
    return 0
  fi

  backup_file "$rc_file"
  {{
    printf '\n# Added by setup_cc_codex.bash\n'
    printf '# Codex uses rustls when SSL_CERT_FILE is set (lyf-expose SAN mismatch workaround).\n'
    printf '%s\n' "$hook_line"
  }} >> "$rc_file"
}}

ensure_linux_ssl_cert_file() {{
  if [[ "$(uname -s)" != "Linux" ]]; then
    return 0
  fi

  ensure_ssl_cert_file_hook "${{HOME}}/.zshrc"
  ensure_ssl_cert_file_hook "${{HOME}}/.bashrc"
}}

main() {{
  ensure_clients

"""

SETUP_SCRIPT_FOOTER = r"""
  ensure_linux_ssl_cert_file
  ensure_user_path_hook "${HOME}/.zshrc"
  ensure_user_path_hook "${HOME}/.bashrc"

  printf '\nClaude Code / Codex proxy setup complete.\n'
  printf 'Proxy URL: %s\n' "$PUBLIC_PROXY_URL"
  printf 'Local proxy port expected by generator: %s\n' "$LOCAL_PROXY_PORT"
  printf 'Claude Code client: %s\n' "$(command -v claude)"
  printf 'Codex client: %s\n' "$(command -v codex)"
}

main "$@"
"""


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description='Generate ~/Downloads/setup_cc_codex.bash for Claude Code/Codex proxy setup.'
	)
	parser.add_argument(
		'--output',
		type=Path,
		default=DEFAULT_OUTPUT_FILE,
		help=f'Output bash script path. Default: {DEFAULT_OUTPUT_FILE}',
	)
	parser.add_argument(
		'--port',
		type=int,
		default=None,
		help=(
			'Local HTTP proxy port. Defaults to the single localhost URL port found in Claude/Codex configs. '
			'Required when local Claude/Codex config files are missing.'
		),
	)
	parser.add_argument(
		'--public-url',
		default=None,
		help='Use an existing public proxy URL instead of starting lyf-expose.',
	)
	parser.add_argument(
		'--include-claude-json',
		action='store_true',
		help='Also package ~/.claude.json. Disabled by default because it contains machine-specific Claude state.',
	)
	parser.add_argument(
		'--include-env-sh',
		action='store_true',
		help='Also package ~/.config/anyrouter-check-in/env.sh if present.',
	)
	parser.add_argument(
		'--plain',
		action='store_true',
		help='Print plain text without rich color panels.',
	)
	return parser.parse_args()


def normalize_public_url(raw_url: str) -> str:
	url = raw_url.strip()
	if not url:
		raise ValueError('public URL is empty')
	if '://' not in url:
		url = f'https://{url}'

	parsed = urlparse(url)
	if parsed.scheme not in {'http', 'https'} or not parsed.netloc:
		raise ValueError(f'invalid public URL: {raw_url}')
	return url.rstrip('/')


def config_specs_from_args(args: argparse.Namespace) -> list[ConfigSpec]:
	specs = list(DEFAULT_CONFIG_SPECS)
	if args.include_claude_json:
		specs.append(OPTIONAL_CONFIG_SPECS['claude-json'])
	if args.include_env_sh:
		specs.append(OPTIONAL_CONFIG_SPECS['env-sh'])
	return specs


def read_config_texts(specs: list[ConfigSpec]) -> tuple[dict[ConfigSpec, str], list[ConfigSpec]]:
	texts: dict[ConfigSpec, str] = {}
	missing: list[ConfigSpec] = []

	for spec in specs:
		if not spec.source.is_file():
			missing.append(spec)
			continue
		texts[spec] = spec.source.read_text(encoding='utf-8')

	return texts, missing


def warn_missing_local_configs(missing: list[ConfigSpec], plain: bool) -> None:
	if not missing:
		return

	lines = '\n'.join(f'  - {spec.source} ({spec.label})' for spec in missing)
	message = (
		'本地未找到以下 Claude/Codex 配置文件，将跳过打包；'
		'生成的脚本仍会安装客户端。\n'
		f'{lines}\n'
		'若无法从现有配置推断代理端口，请使用 --port。'
	)
	if plain:
		print(f'WARNING: {message}', file=sys.stderr)
	else:
		error_console.print(f'[yellow]WARNING:[/] {message}')


def iter_local_proxy_ports(texts: dict[ConfigSpec, str]) -> list[int]:
	ports: list[int] = []
	for content in texts.values():
		for match in LOCAL_HTTP_URL_RE.finditer(content):
			port = int(match.group('port') or '80')
			if port not in ports:
				ports.append(port)
	return ports


def resolve_proxy_port(args: argparse.Namespace, texts: dict[ConfigSpec, str]) -> int:
	if args.port is not None:
		if args.port < 1 or args.port > 65535:
			raise ValueError('--port must be between 1 and 65535')
		return args.port

	ports = iter_local_proxy_ports(texts)
	if len(ports) == 1:
		return ports[0]
	if not ports:
		raise ValueError('could not find a localhost HTTP proxy URL in Claude/Codex configs; pass --port')

	joined = ', '.join(str(port) for port in ports)
	raise ValueError(f'found multiple localhost HTTP ports ({joined}); pass --port to choose one')


def local_port_is_open(port: int) -> bool:
	try:
		with socket.create_connection((DEFAULT_PROXY_HOST, port), timeout=1.5):
			return True
	except OSError:
		return False


def replace_local_proxy_urls(content: str, port: int, public_url: str) -> tuple[str, int]:
	replacements = 0

	def replace(match: re.Match[str]) -> str:
		nonlocal replacements
		match_port = int(match.group('port') or '80')
		if match_port != port:
			return match.group(0)

		replacements += 1
		return f'{public_url}{match.group("suffix") or ""}'

	return LOCAL_HTTP_URL_RE.sub(replace, content), replacements


def build_payloads(texts: dict[ConfigSpec, str], port: int, public_url: str) -> list[ConfigPayload]:
	payloads: list[ConfigPayload] = []
	for spec in texts:
		content, replacements = replace_local_proxy_urls(texts[spec], port, public_url)
		payloads.append(ConfigPayload(spec=spec, content=content, replacements=replacements))
	return payloads


def encode_payload(content: str) -> str:
	encoded = base64.b64encode(content.encode('utf-8')).decode('ascii')
	return '\n'.join(textwrap.wrap(encoded, width=76))


def heredoc_name(spec: ConfigSpec) -> str:
	name = re.sub(r'[^A-Za-z0-9]+', '_', spec.target_rel).strip('_').upper()
	return f'B64_{name}'


def build_setup_script(payloads: list[ConfigPayload], port: int, public_url: str) -> str:
	parts = [
		SETUP_SCRIPT_HEADER.format(
			public_proxy_url=shlex.quote(public_url),
			local_proxy_port=shlex.quote(str(port)),
		)
	]

	for payload in payloads:
		delimiter = heredoc_name(payload.spec)
		parts.append(
			'\n'
			f'  write_config_file "${{HOME}}/{payload.spec.target_rel}" {shlex.quote(payload.spec.mode)} '
			f"{shlex.quote(payload.spec.label)} <<'{delimiter}'\n"
			f'{encode_payload(payload.content)}\n'
			f'{delimiter}\n'
		)

	parts.append(SETUP_SCRIPT_FOOTER)
	return ''.join(parts)


def write_output_script(path: Path, content: str) -> bool:
	previous = path.read_text(encoding='utf-8') if path.is_file() else None
	changed = previous != content

	path.parent.mkdir(parents=True, exist_ok=True)
	path.write_text(content, encoding='utf-8')
	path.chmod(0o700)
	return changed


def render_generation_result(
	path: Path,
	changed: bool,
	payloads: list[ConfigPayload],
	port: int,
	public_url: str,
	plain: bool,
) -> None:
	replaced = sum(payload.replacements for payload in payloads)
	packaged = ', '.join(payload.spec.label for payload in payloads) or '（无，仅安装客户端）'

	if plain:
		if changed:
			print(f'配置文件有更新: {path}')
		else:
			print(str(path))
		print(f'公网地址: {public_url}')
		print(f'本地端口: {port}')
		print(f'已打包: {packaged}')
		print(f'替换 URL 数: {replaced}')
		return

	if changed:
		console.print(f'[yellow]配置文件有更新:[/] [cyan]{path}[/]')
	else:
		console.print(f'[green]{path}[/]')

	body = (
		f'[dim]公网地址[/]  [cyan]{public_url}[/]\n'
		f'[dim]本地端口[/]  {port}\n'
		f'[dim]已打包[/]    {packaged}\n'
		f'[dim]替换 URL[/]  {replaced}'
	)
	console.print(Panel(body, title='setup_cc_codex.bash', border_style='green' if not changed else 'yellow'))


def load_local_config_texts(
	args: argparse.Namespace,
) -> tuple[dict[ConfigSpec, str], list[ConfigSpec]]:
	specs = config_specs_from_args(args)
	texts, missing = read_config_texts(specs)
	warn_missing_local_configs(missing, args.plain)
	return texts, missing


def generate_setup_script(args: argparse.Namespace, public_url: str, port: int) -> tuple[Path, bool, list[ConfigPayload]]:
	texts, _missing = load_local_config_texts(args)
	payloads = build_payloads(texts, port, public_url)
	content = build_setup_script(payloads, port, public_url)
	output = args.output.expanduser()
	changed = write_output_script(output, content)
	return output, changed, payloads


def make_expose_session(port: int, quiet: bool):
	from lyf_expose import ExposeSession

	try:
		return ExposeSession(port, quiet=quiet)
	except TypeError:
		return ExposeSession(port)


def wait_for_interrupt(plain: bool) -> None:
	if plain:
		print('lyf-expose is running. Press Ctrl+C to stop.')
	else:
		console.print('[dim]lyf-expose 正在运行。按 Ctrl+C 结束公网代理并清理本次 NPM 代理。[/]')

	while True:
		time.sleep(3600)


def warn_local_port_if_needed(port: int, plain: bool) -> None:
	if local_port_is_open(port):
		return

	message = f'本机 127.0.0.1:{port} 当前不可连接，请确认 CC switch 代理已启动。'
	if plain:
		print(f'WARNING: {message}', file=sys.stderr)
	else:
		error_console.print(f'[yellow]WARNING:[/] {message}')


def run_with_existing_public_url(args: argparse.Namespace) -> int:
	texts, _missing = load_local_config_texts(args)
	port = resolve_proxy_port(args, texts)
	public_url = normalize_public_url(args.public_url)
	output, changed, payloads = generate_setup_script(args, public_url, port)
	render_generation_result(output, changed, payloads, port, public_url, args.plain)
	return 0


def run_with_lyf_expose(args: argparse.Namespace) -> int:
	texts, _missing = load_local_config_texts(args)
	port = resolve_proxy_port(args, texts)
	warn_local_port_if_needed(port, args.plain)

	if not args.plain:
		console.print(f'[dim]启动 lyf-expose，暴露本机 HTTP 端口 {port}...[/]')

	try:
		session = make_expose_session(port, quiet=args.plain)
	except ImportError as exc:
		raise RuntimeError('lyf-expose 未安装，请先按内部文档安装 lyf-expose。') from exc

	with session as tunnel:
		if not tunnel.urls:
			raise RuntimeError('lyf-expose did not return a public URL')

		public_url = normalize_public_url(str(tunnel.urls[0]))
		output, changed, payloads = generate_setup_script(args, public_url, port)
		render_generation_result(output, changed, payloads, port, public_url, args.plain)
		wait_for_interrupt(args.plain)

	return 0


def main() -> int:
	args = parse_args()
	try:
		if args.public_url:
			return run_with_existing_public_url(args)
		return run_with_lyf_expose(args)
	except KeyboardInterrupt:
		if args.plain:
			print()
		else:
			console.print('\n[dim]已停止 lyf-expose[/]')
		return 130
	except (FileNotFoundError, ValueError, RuntimeError) as exc:
		if args.plain:
			print(f'ERROR: {exc}', file=sys.stderr)
		else:
			error_console.print(f'[bold red]ERROR:[/] {exc}')
		return 1


if __name__ == '__main__':
	raise SystemExit(main())
